//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.27 at 02:41:28 PM CEST 
//


package taskXMLModel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the taskXMLModel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Task_QNAME = new QName("", "task");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: taskXMLModel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StateVariableDefType }
     * 
     */
    public StateVariableDefType createStateVariableDefType() {
        return new StateVariableDefType();
    }

    /**
     * Create an instance of {@link PddlRequirementsListType }
     * 
     */
    public PddlRequirementsListType createPddlRequirementsListType() {
        return new PddlRequirementsListType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link ConstantListType }
     * 
     */
    public ConstantListType createConstantListType() {
        return new ConstantListType();
    }

    /**
     * Create an instance of {@link RelationDefType }
     * 
     */
    public RelationDefType createRelationDefType() {
        return new RelationDefType();
    }

    /**
     * Create an instance of {@link ArgumentType }
     * 
     */
    public ArgumentType createArgumentType() {
        return new ArgumentType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link TaskProperties }
     * 
     */
    public TaskProperties createTaskProperties() {
        return new TaskProperties();
    }

    /**
     * Create an instance of {@link ConstantType }
     * 
     */
    public ConstantType createConstantType() {
        return new ConstantType();
    }

    /**
     * Create an instance of {@link RelationSectionType }
     * 
     */
    public RelationSectionType createRelationSectionType() {
        return new RelationSectionType();
    }

    /**
     * Create an instance of {@link ConstantsSectionType }
     * 
     */
    public ConstantsSectionType createConstantsSectionType() {
        return new ConstantsSectionType();
    }

    /**
     * Create an instance of {@link RowType }
     * 
     */
    public RowType createRowType() {
        return new RowType();
    }

    /**
     * Create an instance of {@link TableType }
     * 
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link StateVariablesSectionType }
     * 
     */
    public StateVariablesSectionType createStateVariablesSectionType() {
        return new StateVariablesSectionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "task")
    public JAXBElement<TaskType> createTask(TaskType value) {
        return new JAXBElement<TaskType>(_Task_QNAME, TaskType.class, null, value);
    }

}
