//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 02:05:14 PM CET 
//


package domainXMLModel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for domainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="domainType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{}domainProperties"/>
 *         &lt;element name="classes" type="{}classTreeType"/>
 *         &lt;element name="relations" type="{}relationListType"/>
 *         &lt;element name="stateVariables" type="{}stateVariableListType"/>
 *         &lt;element name="operators" type="{}operatorListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domainType", propOrder = {
    "properties",
    "classes",
    "relations",
    "stateVariables",
    "operators"
})
public class DomainType {

    @XmlElement(required = true)
    protected DomainProperties properties;
    @XmlElement(required = true)
    protected ClassTreeType classes;
    @XmlElement(required = true)
    protected RelationListType relations;
    @XmlElement(required = true)
    protected StateVariableListType stateVariables;
    @XmlElement(required = true)
    protected OperatorListType operators;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link DomainProperties }
     *     
     */
    public DomainProperties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainProperties }
     *     
     */
    public void setProperties(DomainProperties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the classes property.
     * 
     * @return
     *     possible object is
     *     {@link ClassTreeType }
     *     
     */
    public ClassTreeType getClasses() {
        return classes;
    }

    /**
     * Sets the value of the classes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassTreeType }
     *     
     */
    public void setClasses(ClassTreeType value) {
        this.classes = value;
    }

    /**
     * Gets the value of the relations property.
     * 
     * @return
     *     possible object is
     *     {@link RelationListType }
     *     
     */
    public RelationListType getRelations() {
        return relations;
    }

    /**
     * Sets the value of the relations property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationListType }
     *     
     */
    public void setRelations(RelationListType value) {
        this.relations = value;
    }

    /**
     * Gets the value of the stateVariables property.
     * 
     * @return
     *     possible object is
     *     {@link StateVariableListType }
     *     
     */
    public StateVariableListType getStateVariables() {
        return stateVariables;
    }

    /**
     * Sets the value of the stateVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateVariableListType }
     *     
     */
    public void setStateVariables(StateVariableListType value) {
        this.stateVariables = value;
    }

    /**
     * Gets the value of the operators property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorListType }
     *     
     */
    public OperatorListType getOperators() {
        return operators;
    }

    /**
     * Sets the value of the operators property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorListType }
     *     
     */
    public void setOperators(OperatorListType value) {
        this.operators = value;
    }

}
