/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectRelationsDialog.java
 *
 * Created on Aug 10, 2011, 8:56:13 AM
 */
package ApplicationGUI;

import DataModel.dmRelationTemplate;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author vodrazka
 */
public class SelectRelationsDialog extends javax.swing.JDialog {
    
    private List<dmRelationTemplate> relationDelegates;
    private static DefaultListModel relationListModel = new DefaultListModel();
    private static DefaultListModel selectionListModel = new DefaultListModel();
    
    /** Creates new form SelectRelationsDialog */
    public SelectRelationsDialog(java.awt.Frame parent, boolean modal, List<dmRelationTemplate> relations) {
        super(parent, modal);
        this.relationDelegates = relations;
        
        fillRelationList();
        
        initComponents();   // relationListModel and selectionListModel are set inside
                            // cell renderers are also set
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        excludeButton = new javax.swing.JButton();
        includeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        allExpr = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selExpr = new javax.swing.JList();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Available relations"));

        excludeButton.setText("Exclude");
        excludeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excludeButtonActionPerformed(evt);
            }
        });

        includeButton.setText("Include");
        includeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                includeButtonActionPerformed(evt);
            }
        });

        allExpr.setModel(relationListModel);
        jScrollPane2.setViewportView(allExpr);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(excludeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(includeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excludeButton)
                    .addComponent(includeButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel4.setText("Select relations dialog");

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected relations"));

        selExpr.setModel(selectionListModel);
        jScrollPane1.setViewportView(selExpr);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void includeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_includeButtonActionPerformed
    Object[] selection = allExpr.getSelectedValues();
    
    if (selection.length <= 0)
        return;
    
    for (int i=0; i < selection.length; ++i) {
        selectionListModel.addElement(selection[i]);
    }
    
    fillRelationList();
}//GEN-LAST:event_includeButtonActionPerformed

private void excludeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excludeButtonActionPerformed
    Object[] selection = selExpr.getSelectedValues();
    
    if (selection.length <= 0)
        return;
    
    for (int i=0; i < selection.length; ++i) {
        selectionListModel.removeElement(selection[i]);
    }
}//GEN-LAST:event_excludeButtonActionPerformed

private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
    this.setVisible(false); // setVisible(true) returns now
}//GEN-LAST:event_doneButtonActionPerformed

public static List<dmRelationTemplate> showDialog(java.awt.Frame parent, List<dmRelationTemplate> relations){
    LinkedList<dmRelationTemplate> res = new LinkedList<dmRelationTemplate>();
    SelectRelationsDialog dialog = new SelectRelationsDialog(parent,true,relations);
    
    dialog.setVisible(true);

    for (int i=0; i<selectionListModel.getSize(); ++i) {     // assemble result
        res.add((dmRelationTemplate)selectionListModel.get(i));
    }
    
    relationListModel.clear(); // clear static content
    selectionListModel.clear();
    
    return res;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList allExpr;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton excludeButton;
    private javax.swing.JButton includeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList selExpr;
    // End of variables declaration//GEN-END:variables

    private void fillRelationList() {
        relationListModel.clear();
        
        for (dmRelationTemplate rel: relationDelegates) {
            relationListModel.addElement(rel);
        }
    }
}