/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DomainPropertiesDialog.java
 *
 * Created on Oct 26, 2011, 11:30:25 AM
 */
package ApplicationGUI;

import DataModel.dmDomain;
import java.util.Set;

/**
 *
 * @author fairfax
 */
public class DomainPropertiesDialog extends javax.swing.JDialog {

    dmDomain myDomain = null;
    
    /** Creates new form DomainPropertiesDialog */
    public DomainPropertiesDialog(java.awt.Frame parent, boolean modal, dmDomain targetDomain) {
        super(parent, modal);
        assert(targetDomain != null);
        myDomain = targetDomain;
        initComponents();
        
//        // initialize checkboxes
//        stripsReq.getModel().setSelected(myDomain.getRequirements().contains(dmDomain.STRIPS));
//        typingReq.getModel().setSelected(myDomain.getRequirements().contains(dmDomain.TYPING));
//        objectFluentsReq.getModel().setSelected(myDomain.getRequirements().contains(dmDomain.OBJECT_FLUENTS));
//        equalityReq.getModel().setSelected(myDomain.getRequirements().contains(dmDomain.EQUALITY));
//        // ... more checkboxes
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        domainNameField = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Domain name:");

        domainNameField.setText(myDomain.toString());

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domainNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                    .addComponent(doneButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(domainNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // set new domain name
        myDomain.setDomainName(domainNameField.getText());
        
//        // set requirements
//        Set<Integer> requirementsSet = myDomain.getRequirements();
//        
//        if (stripsReq.getModel().isSelected()) {
//            requirementsSet.add(dmDomain.STRIPS);
//        } else {
//            requirementsSet.remove(dmDomain.STRIPS);
//        }
//        
//        if (typingReq.getModel().isSelected()) {
//            requirementsSet.add(dmDomain.TYPING);
//        } else {
//            requirementsSet.remove(dmDomain.TYPING);
//        }
//        
//        if (objectFluentsReq.getModel().isSelected()) {
//            requirementsSet.add(dmDomain.OBJECT_FLUENTS);
//        } else {
//            requirementsSet.remove(dmDomain.OBJECT_FLUENTS);
//        }
//        
//        if (equalityReq.getModel().isSelected()) {
//            requirementsSet.add(dmDomain.EQUALITY);
//        } else {
//            requirementsSet.remove(dmDomain.EQUALITY);
//        }
//        // ...    
        
        this.setVisible(false); // hide dialog window
    }//GEN-LAST:event_doneButtonActionPerformed

    public static void showDialog(java.awt.Frame parent,dmDomain activeDomain) {
        DomainPropertiesDialog dialog = new DomainPropertiesDialog(parent,true,activeDomain);
        
        dialog.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField domainNameField;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
